files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/%two_letters_code%/values/strings.xml
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
